### ISSUE TITLE
Change out all of the icons in the other components with icon-component

### ISSUE THREAD

**Issue by FabianWilms** [it-at-m/muc-patternlab-vue#104]
Should we change out all of the icons in the other components in this issue/pr or open another?

_Originally posted by @langehm in https://github.com/it-at-m/muc-patternlab-vue/issues/97#issuecomment-2138291357_

**Comment by langehm** [comment]
woups - this cannot be done that easily. Those icons have different "icon-classes" which alter the boldness and size of the icons when used. e.g. 
- m-button__icon is bold
- menu-item is very large
- callout-icon has a box surrounding the icon and moves it

**Comment by FabianWilms** [comment]
But you can add these classes to the icon-component, can't you?

**Comment by langehm** [comment]
yes - i will default to "icon"-class and provide an optional override of this class via props
