### ISSUE TITLE
✨ timepoint selection

### ISSUE THREAD

**Issue by langehm** [it-at-m/muc-patternlab-vue#180]
**Describe the solution you'd like**
Some kind of selection for timepoint (appointement) - could be a subset of the following component from the patternlab
![grafik](https://github.com/user-attachments/assets/b3db1e4b-0f9d-4742-9957-81465a9a6eb2)
Consisting of buttons which change their color depending on the current time.

Subset of the buissnesshour components?

**Comment by lehju** [comment]
Component is too project-specific.
