### ISSUE TITLE
:sparkles: divider component

### ISSUE THREAD

**Issue by langehm** [it-at-m/muc-patternlab-vue#183]
**Describe the solution you'd like**
Divider component as in vuetify
![grafik](https://github.com/user-attachments/assets/db4107b1-3e14-43aa-9be0-62475e70bd42)

**Comment by FabianWilms** [comment]
There already was a css class named muc-divider: https://github.com/it-at-m/muc-patternlab-vue/blob/beta/public/assets/temporary/custom-style.css#L67

Having a component ist better for visibility though. And I just noticed that I got the css wrong by adding a whole border and not just border-bottom :P

But: In it's current implementation a `hr`-tag is used which makes it look wrong in some browsers:

![image](https://github.com/user-attachments/assets/62d60956-1385-41bb-aee3-d19f9356507b)

It's easier to use a div:

![image](https://github.com/user-attachments/assets/3c1819d3-feae-4031-9294-fb08ca0c51b0)
