### ISSUE TITLE
Switch to new destructured property definitions

### ISSUE THREAD

**Issue by FabianWilms** [it-at-m/muc-patternlab-vue#245]
**Is your feature request related to a problem? Please describe.**

Currenlty we get typescript-errors when not using all properties of a component. This is not nice and unwanted.

**Describe the solution you'd like**

Using https://blog.vuejs.org/posts/vue-3-5#reactive-props-destructure can help with this.
Also the new `useTemplateRef` should be used if applicable.

**Component List**

- [x] MucBanner
- [x] MucBusinessHours
- [x] MucButton
- [x] MucCallout
- [x] MucCard
- [x] MucCardContainer
- [x] MucComment
- [x] MucCommentText
- [x] MucDivider
- [x] MucCheckbox
- [x] MucCheckboxGroup
- [x] MucCounter
- [x] MucErrorList
- [x] MucInput
- [x] MucRadioButton
- [x] MucRadioButtonGroup
- [x] MucSelect
- [x] MucSelectItem
- [x] MucTextArea
- [x] MucIcon
- [x] MucIntro
- [x] MucPercentageSpinner

**Comment by langehm** [comment]
We need to change the peer-dependency of vue from `3.4.0` to `3.5.x` - this causes breaking changes.
