### ISSUE TITLE
Integrate prettify check into ci/cd

### ISSUE THREAD

**Issue by FabianWilms** [it-at-m/muc-patternlab-vue#60]
Looking good. I have not checked the css classes any further. The final product looks good, therefore i give my okay.

Please format with prettifier before merging ♥ - done.

_Originally posted by @langehm in https://github.com/it-at-m/muc-patternlab-vue/pull/58#pullrequestreview-2045182760_

**Comment by langehm** [comment]
Instead of manual describing the workflow - this can be done too with this [repository](https://github.com/marketplace/actions/lint-action#javascript-example-eslint-and-prettier)
