### ISSUE TITLE
muc-comment: Limit `initials`-Length

### ISSUE THREAD

**Issue by FabianWilms** [it-at-m/muc-patternlab-vue#74]
Making the `initials` too long leads to a faulty layout:

![image](https://github.com/it-at-m/muc-patternlab-vue/assets/10800158/c7c0774c-bc0a-4f18-9eb4-5246c5d96532)

Should we 

a. fix this by limiting the length
b. fix this by adding custom css which strips text
c. leave it as it is and blame it on patternlab

?

**Comment by langehm** [comment]
Currently two implementation of the comment component exist.
The generic version currently allows any input (via slot) - therefore it would be difficult to restrict the number of characters.

On the other hand, the `MucCommentText`-component allows only text and furthermore generates initials from the authors name. This component could be easily restricted to use 2 (or maybe 3) characters for the initials. This component "extends" the patternlab and therefore it should be okay to add a limit.
