### ISSUE TITLE
Empty author shows empty `initials`

### ISSUE THREAD

**Issue by langehm** [it-at-m/muc-patternlab-vue#80]
**Describe the bug**
When an empty string is choosen for the `author` and `initials`, the circle for the initials is shown empty.

**Expected behavior**
a. Leave it as is
b. Remove the initials-circle
c. blame it on patternlab?

**Screenshots**
![grafik](https://github.com/it-at-m/muc-patternlab-vue/assets/38280183/8cf45dd6-db00-4d3b-8cb1-f98d2362d0e6)

**Comment by FabianWilms** [comment]
I actually think option b) would be great to further extend this components usability.
